package modelo;
// Generated 18/10/2021 09:28:16 PM by Hibernate Tools 4.3.1



/**
 * Cita generated by hbm2java
 */
public class Cita  implements java.io.Serializable {


     private int numCon;
     private Mascota mascota;
     private Usuario usuario;

    public Cita() {
    }

    public Cita(int numCon, Mascota mascota, Usuario usuario) {
       this.numCon = numCon;
       this.mascota = mascota;
       this.usuario = usuario;
    }
   
    public int getNumCon() {
        return this.numCon;
    }
    
    public void setNumCon(int numCon) {
        this.numCon = numCon;
    }
    public Mascota getMascota() {
        return this.mascota;
    }
    
    public void setMascota(Mascota mascota) {
        this.mascota = mascota;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }




}


