package modelo;
// Generated 17/10/2021 06:08:47 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Rol generated by hbm2java
 */
public class Rol  implements java.io.Serializable {


     private int idRol;
     private String rol;
     private Set usuarios = new HashSet(0);

    public Rol() {
    }

	
    public Rol(int idRol, String rol) {
        this.idRol = idRol;
        this.rol = rol;
    }
    public Rol(int idRol, String rol, Set usuarios) {
       this.idRol = idRol;
       this.rol = rol;
       this.usuarios = usuarios;
    }
   
    public int getIdRol() {
        return this.idRol;
    }
    
    public void setIdRol(int idRol) {
        this.idRol = idRol;
    }
    public String getRol() {
        return this.rol;
    }
    
    public void setRol(String rol) {
        this.rol = rol;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }

    @Override
    public String toString() {
        return "Rol{" + "idRol=" + idRol + ", rol=" + rol + ", usuarios=" + usuarios + '}';
    }




}


