package modelo;
// Generated 18/10/2021 09:28:16 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int idUsuario;
     private Rol rol;
     private String direccion;
     private String nombre;
     private String apellido;
     private Date fechaNacimiento;
     private String especialiicion;
     private String cargo;
     private Set citas = new HashSet(0);
     private Set mascotas = new HashSet(0);
     private Set historials = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(int idUsuario, Rol rol, String direccion, String nombre, String apellido, Date fechaNacimiento, String especialiicion, String cargo) {
        this.idUsuario = idUsuario;
        this.rol = rol;
        this.direccion = direccion;
        this.nombre = nombre;
        this.apellido = apellido;
        this.fechaNacimiento = fechaNacimiento;
        this.especialiicion = especialiicion;
        this.cargo = cargo;
    }
    public Usuario(int idUsuario, Rol rol, String direccion, String nombre, String apellido, Date fechaNacimiento, String especialiicion, String cargo, Set citas, Set mascotas, Set historials) {
       this.idUsuario = idUsuario;
       this.rol = rol;
       this.direccion = direccion;
       this.nombre = nombre;
       this.apellido = apellido;
       this.fechaNacimiento = fechaNacimiento;
       this.especialiicion = especialiicion;
       this.cargo = cargo;
       this.citas = citas;
       this.mascotas = mascotas;
       this.historials = historials;
    }
   
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public String getEspecialiicion() {
        return this.especialiicion;
    }
    
    public void setEspecialiicion(String especialiicion) {
        this.especialiicion = especialiicion;
    }
    public String getCargo() {
        return this.cargo;
    }
    
    public void setCargo(String cargo) {
        this.cargo = cargo;
    }
    public Set getCitas() {
        return this.citas;
    }
    
    public void setCitas(Set citas) {
        this.citas = citas;
    }
    public Set getMascotas() {
        return this.mascotas;
    }
    
    public void setMascotas(Set mascotas) {
        this.mascotas = mascotas;
    }
    public Set getHistorials() {
        return this.historials;
    }
    
    public void setHistorials(Set historials) {
        this.historials = historials;
    }




}


